#!/bin/bash

OUT="./boot/kernel_size.asm"

echo "; KalioOS (C) Pranav Bagur $(date)" > $OUT
echo "; This is an autogenerated file" >> $OUT
echo "; Do not casually replace this" >> $OUT
printf "KERNEL_SIZE equ 0x%x\n" $(((`stat --printf="%s" kernel.bin` + 511) / 512)) >> $OUT
chmod 777 $OUT
